version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "installing sam"
      - pip install --upgrade pip
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "running no pre build"
  build:
    commands:
      - echo build started at `date` for environment $ENV_NAME
      - sam package --s3-bucket chathura-gateway-static --template-file template.yaml --output-template-file chathura-static-package.yaml
      - echo "deploying"
      - sam deploy --template-file chathura-static-package.yaml --stack-name chathura-static-gateway --capabilities CAPABILITY_IAM
  post_build:
    commands:
      - echo deployment completed at `date`
